apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: logging-kibana
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/0mar1010/DevOps-Final-Project
    targetRevision: main
    path: charts/kibana
    helm:
      values: |
        elasticsearchHosts: "http://elasticsearch-master:9200"
        resources:
          requests:
            cpu: "100m"
            memory: "512Mi"
          limits:
            cpu: "500m"
            memory: "1Gi"
        ingress:
          enabled: true
          ingressClassName: traefik
          hosts:
            - host: kibana.local
              paths:
                - path: /
  destination:
    server: https://kubernetes.default.svc
    namespace: logging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true