apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: task-manager-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/0mar1010/DevOps-Final-Project.git
    targetRevision: main
    path: K8s/overlays/staging
  destination:
    server: https://kubernetes.default.svc
    namespace: microservices
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true