apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

labels:
- pairs:
    environment: staging
images:
- name: backend
  newName: ghcr.io/0mar1010/backend
  newTag: e491fcaacbf13912db074b4c46f186b1e84a7278
- name: frontend
  newName: ghcr.io/0mar1010/frontend
  newTag: e491fcaacbf13912db074b4c46f186b1e84a7278
