apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

labels:
- pairs:
    environment: staging
images:
- name: backend
  newName: ghcr.io/0mar1010/backend
  newTag: 85370f1ab58fddeed8c6eb3ab08cbd2cd01f372a
- name: frontend
  newName: ghcr.io/0mar1010/frontend
  newTag: 85370f1ab58fddeed8c6eb3ab08cbd2cd01f372a
