apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

labels:
- pairs:
    environment: staging
images:
- name: backend
  newName: ghcr.io/0mar1010/backend
  newTag: 7a00718dc4366793eb1cf07554b98423be38f719
- name: frontend
  newName: ghcr.io/0mar1010/frontend
  newTag: 7a00718dc4366793eb1cf07554b98423be38f719
